version: "3.7"

services:
  db:
    image: postgres:15.4-alpine3.17
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_manager
    ports:
      - "5432:5432"

volumes:
  data: